<%@ Page Title="Home Page" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.vb" Inherits="IOT._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <script src="Scripts/progressbar.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">        
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.sendMessage = function (message) {
                // Html encode display name and message. 
                if (message == "Update") {
                    Sys.WebForms.PageRequestManager.getInstance().beginAsyncPostBack(
                        [ '<%=upActual.ClientID %>' ], '<%=upActual.ClientID %>', null
                    );
                }
            };
            $.connection.hub.start().done(function () {
                
            });
        });
        var bar;
        function timerProgress(){
            bar= new ProgressBar.Circle('#timerProgress', {
                color: '#00FF00',
                trailColor: 'gray',
                // This has to be the same size as the maximum width to
                // prevent clipping
                strokeWidth: 5,
                trailWidth: 5,
                easing: 'easeInOut',
                duration: 1400,
                text: {
                    autoStyleContainer: false
                },
                from: { color: '#90EE90', width: 5 },
                to: { color: '#00FF00', width: 5 },
                // Set default step function for all animate calls
                step: function (state, circle) {
                    circle.path.setAttribute('stroke', state.color);
                    circle.path.setAttribute('stroke-width', state.width);

                    var value = Math.round(circle.value() * 100);
                    if (value === 0) {
                        circle.setText('');
                    } else {
                        circle.setText(value + "<span style='font-size:3vmin'>%<span>");
                    }

                }
            });
            bar.text.style.fontSize = '7vmin';
        };
        var x;
        var previousTimerPercentage = 0;
        var previousIdealData = 0;
        var previousDiffData = 0;
        function updateData(planData, resultData) {
            if (x) {
                clearInterval(x);
            }            
            var currentDateTime = new Date();
            var startDateTime = new Date();
            var endDateTime = new Date();
            startDateTime.setHours(8, 0, 0);
            endDateTime.setHours(17, 0, 0);
            var fullTime = endDateTime.getTime() - startDateTime.getTime();
            x = setInterval(function () {
                var now = new Date();

                // Find the distance between now an the count down date
                var distance;
                if (now.getHours() < 8 || now.getHours() > 17) {
                    distance = fullTime;
                }
                else {
                    distance = now.getTime() - startDateTime.getTime();
                }

                // Output the result in an element with id="demo"
                document.getElementById("timer").innerHTML = now.getDate() + "/" + (now.getMonth() + 1) + "/" + now.getFullYear() + "\n" + now.getHours() + ":" + now.getMinutes() + ":" + now.getSeconds();
                var timerPercentage = Math.floor((distance / fullTime) * 100)/100;
                var idealData = Math.floor(planData * timerPercentage);
                var diffData = resultData - idealData;
                if (previousIdealData == 0) {
                    document.getElementById("<%= lbIdeal.ClientID%>").classList.add("fadeInLabel");
                    document.getElementById("<%= lbIdeal.ClientID%>").innerHTML = idealData;
                    previousIdealData = idealData;
                }
                else {
                    if (idealData != previousIdealData) {
                        document.getElementById("<%= lbIdeal.ClientID%>").classList.add("fadeInLabel");
                        document.getElementById("<%= lbIdeal.ClientID%>").innerHTML = idealData;
                        previousIdealData = idealData;
                    }
                }

                if (previousDiffData == 0) {
                    if (diffData < 0) {
                        document.getElementById("<%= lbDiff.ClientID%>").style.color = "red";
                    }
                    else {
                        document.getElementById("<%= lbDiff.ClientID%>").style.color = "#00FF00";
                    }
                    document.getElementById("<%= lbDiff.ClientID%>").classList.add("fadeInLabel");
                    document.getElementById("<%= lbDiff.ClientID%>").innerHTML = diffData;
                    previousDiffData = diffData;
                }
                else {
                    if (diffData != previousDiffData) {
                        if (diffData < 0) {
                        document.getElementById("<%= lbDiff.ClientID%>").style.color = "red";
                        }
                        else {
                            document.getElementById("<%= lbDiff.ClientID%>").style.color = "#00FF00";
                        }
                        document.getElementById("<%= lbDiff.ClientID%>").classList.add("fadeInLabel");
                        document.getElementById("<%= lbDiff.ClientID%>").innerHTML = diffData;
                        previousDiffData = diffData;
                    }
                }
                
                if (previousTimerPercentage == 0) {
                    bar.animate(timerPercentage);
                    previousTimerPercentage = timerPercentage;
                }
                else {
                    if (timerPercentage != previousTimerPercentage) {
                        bar.animate(timerPercentage);
                        previousTimerPercentage = timerPercentage;
                    }
                }
            }, 1000);
        };
               
    </script>
    <link href="Content/MyStyle.css" rel="stylesheet" />
    <div class="drawBorder">
        <table class="tableDefaultBoard">
            <tr>
                <td></td>
                <td>PLAN</td>
                <td>
                    <asp:Label ID="lbPlan" CssClass="fadeInLabel" runat="server" Text=""></asp:Label>
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>IDEAL</td>
                <td>
                    <asp:Label ID="lbIdeal" runat="server" Text=""></asp:Label>
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>ACTUAL</td>
                <td>
                    <asp:UpdatePanel ID="upActual" runat="server" AssociatedUpdatePanelID="upActual">            
                        <ContentTemplate>
                            <asp:Label ID="lbActual" CssClass="fadeInLabel" runat="server" Text=""></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>DIFF</td>
                <td>
                    <asp:Label ID="lbDiff" runat="server" Text=""></asp:Label>
                </td>
                <td>
                    <div id ="timerProgress"></div>
                    <p id="timer" style="color:white;font-size:2vmin"><%=Date.Now.ToString("d/M/yyyy h:m:s") %></p>
                </td>
            </tr>
        </table>
    </div>
    <script type="text/javascript">
        timerProgress();
        document.getElementById('<%= lbIdeal.ClientID%>').addEventListener('webkitAnimationEnd', function(){
            document.getElementById("<%= lbIdeal.ClientID%>").classList.remove("fadeInLabel");
        }, false);
        document.getElementById('<%= lbDiff.ClientID%>').addEventListener('webkitAnimationEnd', function(){
            document.getElementById("<%= lbDiff.ClientID%>").classList.remove("fadeInLabel");
        }, false);        
    </script>
</asp:Content>
